const BRACKET_COORDINATES = {
    FIRST_ROUND_X: 0,
    X_STEP: 10,

    FIRST_ROUND_Y_GAP: 20,
    SECOND_ROUND_Y_GAP: 30,
    SWEET_SIXTEEN_Y_GAP: 40,
    ELITE_EIGHT_Y_GAP: 50,
    FINAL_FOUR_Y_GAP: 60,

    FIRST_ROUND_Y_STEP: 10,
    SECOND_ROUND_Y_STEP: 15,
    SWEET_SIXTEEN_Y_STEP: 20,
    ELITE_EIGHT_Y_STEP: 25,
    FINAL_FOUR_Y_STEP: 30,
    CHAMPIONSHIP_Y: 300
}

export default BRACKET_COORDINATES;